### PR TITLE
Ka add user course

### PR DESCRIPTION
**Pull request by kimiaf1998**
Added role type for users being added to a course by an instructor

### CODE REVIEW

**Comment by reznikovl** [comment]
Thanks Kimia - most of the changes LGTM. The only thing is I think some logic needs to be added into the course page about whether someone can leave as a TA. Currently, students can leave and instructors cannot, but the section for TAs is blank:

image

**Comment by kimiaf1998** [comment]
Humm, you are right. I think I need to let TAs leave the course too.

**Comment by kimiaf1998** [comment]
Fixed. Pls, review it again. Thank you

**Comment by reznikovl** [comment]
LGTM! Thanks for the changes

**Pull request merged**
